language: generic

sudo: true

python:
  - "3.7"

addons:
  apt:
    sources:
    - deadsnakes
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    - sourceline: 'deb https://packagecloud.io/chef/stable/ubuntu/precise main'
      key_url: 'https://packagecloud.io/gpg.key'
    packages:
      - "python3"
      - "python3-pip"

install:
    - mkdir ~/.config/nvim
    - git clone --depth=1  https://github.com/hardcoreplayers/ThinkVim ~/.config/nvim
    - nvim

before_install:
    - sudo apt-get install neovim
    - pip3 install --user pynvim
    - pip3 install neovim-remote
    - nvim --version

notifications:
  email: false
